### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by deepaksivadas** [kirk86/ImageRetrieval#5]
Pls, let us know which file is to be run. All '.m' files are functions.

**Comment by kirk86** [comment]
@deepaksivadas the steps are listed below.
1. run the `cbires.m` file, it will open the GUI program
2. load the dataset, those are files ending in `.mat`
3. choose an image and execute the query to fetch similar ones

**Comment by shiv1sunka** [comment]
what should be the image database path? i get an error dailog saying no query image selected, and whats the role of dataset?

**Comment by shiv1sunka** [comment]
please mention all the toolboxes required as well.

**Comment by kirk86** [comment]
> what should be the image database path?

Are you asking about the database path related to the feature dataset created from your own set of images?


> I get an error dailog saying no query image selected, and whats the role of dataset?

Make sure you read and understand the steps detailed in an earlier comment on this thread.
Since this is a content based image retrieval, (i.e.) given an image fetch similar ones, the `no query image selected` error is not an error but a prompt to remind you to select an image to be used as query against the dataset (`whats the role of dataset?`) in order to retrieve similar ones from that prepossessed dataset.

 > please mention all the toolboxes required as well.

Unfortunately I can't recall all of them, but if you have the wavelet and computer vision toolbox you'll probably covered though.

**Comment by shiv1sunka** [comment]
thanks. i got that part.
now, in the svm.m i get the error saying svmtrain is an undefined function or variable in line 53.
please reply at the earliest. thankyou.
![Screenshot (26)](https://user-images.githubusercontent.com/49687396/56426377-c853c500-62d5-11e9-8514-b680b9dd42c0.png)

**Comment by kirk86** [comment]
> now, in the svm.m i get the error saying svmtrain is an undefined function or variable in line 53

Yup, that's matlab's fault, what happened is that earliest version of matlab have completely removed `svmtrain` method and replaced it with `fitcsvm`. Since you're using a very recent version of matlab you'll have to modify the code and replace `svmtrain` with `fitcsvm`.

**Comment by shiv1sunka** [comment]
thankyou so much :)
